version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    restart: always
    command: uvicorn journal_api:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./journal-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./journal-frontend:/app
      - /app/node_modules   # avoids overwriting installed packages
    working_dir: /app
    restart: always
    command: sh -c "npm install && npm start"
    stdin_open: true
    tty: true
